---
title: Differential analysis in the RNASeq bulk pipeline
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Differential analysis in the RNASeq bulk pipeline}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
author: Gavin Kelly
---

## Analysis Philosophy

This is a wrapper round DESeq2 which standardises the process of
generating `DESeq2::results` objects for a specifiable set of
comparisons. Each comparison is done in the context of a model (a
specification of what covariates need to be accounted for in
predicting the expression of any transcript). And each model is
formulated in a sample-set (which is usually all the samples, but can
be changed to drop samples, or look at a stratum in an isolated way).

There are three classes of input to the analysis pipeline: the raw
count files; the experiment table; and an analysis specification. The
count files should be stored in a folder
`extdata/alignmentID/genes.results/` relative to the analysis home
directory, where `alignmentID` is a freeform name that identifies the
alignment settings and choices (so could just be 'nfcore', or a
species name, or a version number of a reference ...).

The experiment table is called `extdata/metadata_alignmentID.csv` (to
match with the choice of the folder name above) and the first column
should be called `ID` and identifies the sample that a row is
describing, so if `extadata/nfcore/genes.results/A1.genes.results` is
sample A1 that is a control, then `extdata/metadata_nfcore.csv` should
start

```
ID,treatment,...
A1,control,...
```

Other columns should be used to entirely describe the experimental
state of the sample that might have an influence on expression. There
is a convention that the first column _after_ `ID` which takes on
unduplicated values throughout the rows is to be used as the sample
label in plots (e.g. a `samplename` column 2.) If there is no such
column, the `ID` column will be used.  In either case, the label will be
shorn of any common prefix, so if the IDs are SAMP9999A1
... SAMP999A10, and no other unduplicated column is stored, then the
samples will be labelled 1...10).


The plan as to what analyses are to be carried out is stored in
a `.spec` file, and there can be as many of these as you want - so you
could have an `overview.spec` file that tried out a handful of
approaches, and a `publication.spec` that recorded the chosen
approach. Each `.spec` file is in fact an R script (and so should be
treated with as much caution, security-wise, as any other script), but
is expected to be of a certain form, the first criterion is that it
should start and end as follows:

```r
specification(
...
)
```

### Sample sets
The highest level of any standardised analysis is a choice as to what
samples are to be analysed together. Often this is trivial, and the
only sensible analysis is to look at all the samples together. But
even in the simplest experiment, it might be observed for example that
one sample is an outlier and we'd like to examine the effect of
omitting or retaining this sample. We can accomplish this easily:

```r
specification(
  sample_sets =list( 
    all = sample_set(
      subset = TRUE
    ),
    no_outlier=sample_set(
    subset = sample_id != "id_of_bad_sample"
    )
  )
)
```

So a collection of samples is called a `sample_set`, and we have two
(a `list`) of them here. The `subset` expression of a sample\_set is
evaluated in the context of the `colData`, so the first one always
evaluates to `TRUE`, denoted that we include all samples; the second
one evaluates to `FALSE` for a particular sample (assuming we have a
sample\_id column in our `colData`), dropping that sample.

Other reasons we may want to subset our samples into different
configurations is: if there are two very different cohorts of samples
where transcripts are likely to have substantially different noise
profiles and we want to avoid contaminating one set of samples with
the estimates of dispersion that hold for the other set. Of course it
then becomes impossible to _statistically test_ between the two
cohorts, but we can have a third set that still combines them:

```r
specification(
  sample_sets =list( 
    all = sample_set(
      subset = TRUE
    ),
    tumour=sample_set(
      subset = condition == "tumour"
    ),
    normal=sample_set(
      subset = condition == "normal"
    )

  )
)
```

The conditions on which we subset must be defined in the experiment
table. It is possible to transform some of the predictors (columns of
`colData`) at this stage, which offers an alternative way of
subsetting as well, but we will (describe this)[later]. For now
we'll look at the main analysis attribute of a sample set, namely the
model we'll use to estimate the expression in the various experimental
conditions those samples were taken from:

### Models

DESeq2 uses R's standard one-sided formulas to inform the analysis as
to which predictors to use in fitting a negative-binomial model of
expression counts. The `colData` slot should contain all the potential
predictors, and the `design` slot of a DESeq2 object encodes a
considered choice of which are relevant to the biological
question. Obviously, if the question is to find which genes are
differentially expressed between two treatments, then a predictor
annotating which treatment a sample is subject to is necessary. But
quite often there will be other covariates need to be accounted for,
such as batch; or perhaps there's a subtler question of finding genes
that respond differently to treatment depending on the genotype of the
sample.

We may want to consider alternative models, for instance whether or
not to include a batch effect: if the batch effect is negligible we
won't want to use up degrees of freedom (ie power) estimating it, but
if it's substantial then we want to make our estimates more precise by
accounting for it. So we allow, in any given sample_set, for there to
be multiple models:

```r
specification(
  sample_sets =list( 
    all = sample_set(
      subset = TRUE,
      models = list(
        accurate = model(
          design = ~treatment + batch
        ),
        powerful = model(
          design = ~treatment
        )
      )
    )
  )
)
```

So once again the plural 'models' is a list of individual `model`
objects, which for the moment we've just specified by their `design`,
exactly as we would for a `DESeq` object. Once we have a model, we are
then in a position to test the significance of contrasts (e.g.
individual log fold-changes between conditions) and terms in the model
(e.g whether batch effect is necessary or not):

### Comparisons

DESeq2 has multiple ways of specifying a contrast. All of these are
supported, and again as 'comparisons' is plural, we can have a list of
them, and have the pipeline loop through all of them for the parent
model:

```r
specification(
  sample_sets =list( 
    all = sample_set(
      subset = TRUE,
      models = list(
        accurate = model(
          design = ~treatment + batch,
          comparisons = list(
            comp1 = "treat_vs_ctrl",
            comp2 = c("treatment", "treat", "ctrl"),
            comp3 = list(c("treat_vs_ctrl"), c("vehicle_vs_ctrl"), listValues=c(1,-1))
            comp4 = c(1,0,-0.5,-0.5),
			comp5 = ~batch
          )
        )
      )
    )
  )
)
```

So all of the traditional ways of specifying a contrast are
represented, respectively:

- by a single character, traditionally done in DESeq2 with
  `results(..., name="treat_vs_ctrl")`
  
- A character triplet

- A two-component list of characters indicating the numerator and
  denominator (with possible `listValues` set)
  
- A numeric vector.

- A formula specifying the `reduced` term for carrying out Anova via
  a likelihood ratio test.

You are referred to the DESeq2 reference manual for further details,
but one advantage of our wrapper is that it allows a simple enumeration
of complex comparisons using machinery from the `emmeans` package:

#### Automatic comparison enumeration

We often find ourselves copying a contrast multiple times, with slight
changes to elicit comparisons between different conditions. For
example if our samples have been subject to three different treatment
regimes, and a control, so treatment={_control_, _vehicle_,
_standard_, _novel\_treatment_}, and we wanted to compare everything to
_control_, then we'd need to hand-write three comparisons. Instead we
can now write

```r
specification(
  sample_sets =list( 
    all = sample_set(
      subset = TRUE,
      models = list(
        accurate = model(
          design = ~treatment + batch,
          comparisons = list(
            mult_comp(trt.vs.ctrl ~ treatment, ref="control")
          )
        )
      )
    )
  )
)
```

where the `trt.vs.ctrl` is a 'keyword' instructing as to which comparisons to
carry out - in this case every value of `treatment` against the ones
labelled "control". There are a number of other helpful keywords:

- `revpairwise` is the most 'verbose', in that it will generate every
  pair of comparisons, in this case there are six combinations, and it
  can go up rapidly. Due to a slightly annoying convention, `pairwise`
  choses an unintuitive ordering that would result in comparisons such
  as 'control vs novel\_treatment' (and a positive fold change would mean
  higher expression in the control than the novel treatment), and
  `revpairwise` has the more conventional ordering of
  'novel\_treatment vs control' and it's more intuitive positive log
  fold-change indicating higher expression in the treated to the
  control. This assumes the levels of the factor are given in the
  conventional order of the previous paragraph.
  
- `consec` takes adjacent pairs along the levels, so again quite a
  natural 'vehicle vs control', 'standard vs vehicle' and finally
  'novel\_treatment vs standard'
  
- `trt.vs.ctrl` chooses one baseline (which we can select with an
  additional `ref` argument, rather than having to `relevel` the data)
  and compares everything else against it.
  
- `mean_chg` looks to see if splitting the levels at any particlar
  point reveals a change between levels before vs after that
  breakpoint, so amongst other things would test if the average of the
  _vehicle_ and _control_ was different from the average of the
  _standard_ and _novel_ treatment.
  
- `eff` tests whether each individual level is different from the
  average of the remaining levels.

These latter two still estimate the _standard error_ in the individual
experimental groups, so the significance is still assessed relative to
replicate variability. This is different from 'relabelling' the
samples (via a `transform`) so that e.g. there was one group called
"both controls" and another called "both treatments", where the
standard error would include not only the 'true' replicate variability
but also the discrepancy between the former experimental groups that
have now been pooled.

When we don't have an interaction term in our model, this is
everything we'd ever need, as for example the difference between
'novel\_treatment' and 'control' is by construction (of the model
formula) independent of which batch we're in.

#### Interaction terms

When our model includes an interaction between two main effects, say
between treatment and genotype, then the magnitude of difference
between two treatments can depend on the genotype. This leads to two
types of follow-up question: stratifying the data by one factor, and
then examining the effect of the other factor in each individual
stratum, or; examining the interaction itself, so looking to see if
the magnitude of effect is different in one stratum than another.

To make this more concrete for the genotype x treatment case, we could
ask: which genes are responding to treatment in the KO; which genes
are responding to treatment in the WT; which genes are differential
between WT and KO in the untreated. These are all questions of the
first type, and we can automatically generate their contrasts by:

```r
specification(
  sample_sets =list( 
    all = sample_set(
      subset = TRUE,
      models = list(
        accurate = model(
          design = ~treatment *  genotype,
          comparisons = list(
            mult_comp(revpairwise ~ treatment | genotype)
            mult_comp(revpairwise ~ genotype  | treatment)
          )
        )
      )
    )
  )
)
```

so the `|` symbol is to be read as "stratified by" (or "conditioned
on"). The first `mult_comp` is stratifying the genotype, and will
generate the pairwise comparisons within treatment, separately for
each different genotype. The second is the dual question: For each
treatment, find the genes that are 'markers of genotype' within that
treatment group.

The second type of question, where we want to investigate a
'difference of differences', is achieved by the following grammar:

```r
mult_comp(revpairwise+revpairwise ~ treatment + genotype, interaction=TRUE)
```

The terms on the right hand side of the formula enumerate the
predictors we're concerned in (there's no need to have their
interaction - that's already known because of the `design`), and the
left hand side specifies the contrasts that are going to be considered
(so any of the keywords from the previous section) - there needs to
be either one (which will be applied to all predictors), or one per
factor on the other side of the formula (as here) in the respective
order.

The above is probably quite intimidating, so please ask for help on
this - I'll try to write something a bit more friendly.

#### Caveat

With the ease of testing so many hypotheses comes a risk of fishing
the data, resulting in spurious statistical associations. Strictly
speaking, anything beyond one comparison on the data requires a more
conservative approach than is achieved even with the traditional
control for FDR to account for the multiplicity of genes.

The ideal situation is the tests are prespecified. If that is the
case, then we should really run an anova to confirm that a change
exists somewhere, and then do at most n-1 comparisons
(where n is the number of levels in the factor of interest, so at most
three comparisons for our four-treatment example) and choose
transcripts where both the anova and contrast are significant. There's
a further technical constraint that the comparisons should be
independent but that is often ignored. If there are more comparisons
of interest, then the p-values won't be controlled at the correct
rate.

Often, the ideal situation is not achieved, and an exploratory
approach is requested. Being strict one should immediately correct for
the abundance of hypotheses in this situation. Pragmatically and
traditionally we neither adjust in this situation nor consider
possible adjusting in the pre-specificied case - this means that the
p-values aren't correctly calibrated, and one of the reasons why I
discourage presenting them in any quantitative form as part of the
results.

Also remember the "Table Two Fallacy" - any inference made about
non-randomly-allocated groups is an observational finding, and doesn't
carry the same rigour as inferences where treatment was randomly
allocated. Observations of associations can easily be spurious and
non-causal.

### Rank deficiency 

One of the most common hurdles in complex designs is the
rank-deficiency problem. The way the experiment has been described can
result in the analysis struggling to identify an estimate for a
particular experimental condition. This happens for one of three
reasons:

- The design has a fatal flaw. If all your treated samples are in one
  batch, and all your control samples in another batch, you cannot
  estimate the extent on how these individually influence expression.
  
- Some conditions have no samples. For example, in our genotype x
  treatment experiment, we might not have a 'vehicle' treatment in one
  of our genotypes.
  
- There is a nesting indicative of repeated measurements. Individuals
  might have submitted multiple samples (perhaps a time-course), and
  also be members of larger groups (their disease status, which is
  assumed constant throughout the time-course).
  
The latter two are remediable through some tweaks to the inputs of
DESeq2, the first will need the advice of a statistician to see if
anything is recoverable and at what compromise.

The 'missing condition' case is easily remedied by supplying the
option `drop_unsupported_combinations=TRUE` to any _model_ you want
this to apply to. The 'nesting' case normally requires a tweak to the
way factors are coded, and we have made it easy to achieve this
through a `transform` option to any _sample\_set_.  Both options are
illustrated below. Note, it is important that there be only **one**
`transform=mutate` component per sample_set (if you want to
introduce/transform multiple derived covariates, then separate them by
commas _within_ the `mutate` expression:

```r
specification(
  sample_sets =list( 
    all = sample_set(
      subset = TRUE,
      transform = mutate(unit = recode_within(unit, genotype),
	                     time = as.numeric(sub("^t", "", timepoint))),
      models = list(
        nested = model(
          design = ~timepoint *  genotype + person:genotype,
          comparisons = list(
            mult_comp(revpairwise ~ timepoint | genotype)
          ),
          drop_unsupported_combinations=TRUE
        )
      )
    )
  )
)
```

The 'missing condition' case is achieved by just the one line; the
nesting is more complex - we firstly have to have a 'unit' column in
our `colData` that identifies which biological unit (person, animal,
plate) a sample belongs to. Then the `transform` line calls a `recode_
within` function that tells us that unit is nested within genotype
here. And we alter the `design` in accordance with the DESeq2 vignette
on within- and between- group comparisons.

The `transform` statement can be used to adjust any of the `colData`
columns in-line. It's a question of personal preference whether
'mistakes' in the original experiment table should be fixed at source
(which allows the scientist to review changes manually), or via a
transformation specified in the spec file (which keeps an entirely
faithful record of what is done).

There's another use of the `transform` option - if it generates a
covariate called `.include` this will be used to further subset the
data so one can analyse a subset of the data based on a criterion
derived from, but not explicitly present, in the experiment table.

### Other functionality

#### QC Formulae

In the exploratory plots, we present PC and dendodrograms. Primarily
these are of the normalised counts without any further processing, but
there is a mechanism for removing the effect of known covariates prior
to the calculation of variable genes (for heatmaps) and rotations (for
PCs). This is useful in cases where the dominant transcriptional
variation might be driven by "nuisance" covariates, such as batch or
patient, and so the simply normalised plots focus on experimentally
uninteresting features.

This is **not** the same as looking at an unadjusted PCA plot,
noticing that the main clusters appear to relate to batch, and the
then noticing that, say, timepoint rather than treatment is
determining the subclusters within the large clusters, and from this
saying that timepoint is more "important" than treatment. That is a
fallacy, as the original dimension reduction is looking in the "wrong"
direction. Recalculating the PCs having removed the nuisance effect is
more valid.

By default, in any given `sample_set`, the first model design will be
captured and used as the basis for covariate adjustment prior to
PC/Heatmap generation. And "partial residuals" for each term in the
model are calculated.  So if the first model for a dataset had a
design `~ treatment * time + batch`, we'd generate three PC plots: one
where the time and batch effect had been removed, and then colouring
by treatment; one coloured by time (having removed treatment and batch
effects); and one coloured by batch (having removed the two
experimental conditions).

But we can be more general than this.  Say we wanted to look purely at
the effect of solely removing 'batch' - this is available by setting a
`qc_formulae` argument in the model

```
    all = sample_set(
      subset = TRUE,
      models = list(
        nested = model(
          design = ~treatment * time + batch,
          qc_formulae= treatment + time ~ timepoint * time,
	  ...
```

Everything on the LHS is used, in turn,  as a "colouring" of the PCs
that have been calculated on data that have been "reconstructed" using
the terms on the RHS of the qc formula.  So this would
give us two plots (one for each experimental condition) having removed
the "nuisance" batch effect (as that is the only term from the design
formula that is missing from the qc formula.)  The "reconstruction" is
done based on the fitting of the `design` formula, so the qc formula
will need to be a sub-model of the design (akin to DESeq2's LRT
specification): each gene's predicted value (based on terms in the qc
formula) is supplemented with the "residual error", to retain the
sample-to-sample variability.

We can have multiple formulae (hence the spelling!) 

```
    all = sample_set(
      subset = TRUE,
      models = list(
        nested = model(
          design = ~treatment * time + batch,
          qc_formulae= list(
		    treatment + time ~ treatment * time,
		    batch + treatment + time ~ treatment + time),
	  ...
```

The first one has just been described; the second one removes the
effect of batch _and_ the time:treatment interaction. It produces
three plots, colouring exactly the same PCA by batch, treatment and
time in turn.  If we want to distinguish two covariates on the same
plot, we can change the shape by adding an interaction on the LHS,
e.g.

```
qc_formulae = treatment:batch + time:batch ~ ...
```

where the first term determines the colour aesthetic, and the second
the shape aesthetic - each 'summand' separated by a `+` will result in
a separate plot.
   
One final feature is that if we omit the `qc_formulae` entirely for
all models in a dataset, then the design of the first model will be
utilised - all its main effects will be captured, so a `design =
~treatment * time + batch` has three first order terms, resulting in

```
qc_formulae= treatment + time + batch ~ 0
```

The `0` on the RHS is a special construct - it means when colouring by
a covariate, that covariate's effect will automatically be added back
in, so is equivalent to 

```
qc_formulae = list(
treatment ~ treatment, 
time ~ time,
batch ~ batch
)
```

which in turn is equivalent to the old "Focussed on" mechanism. If for
some reason you want to visualise the effect of removing _all_
covariates defined in the design, the a qc formula of e.g. `time ~ 1`
will achieve that. If this PCA falls into clusters, then chosing a
previously ignored column of sample metadata instead of `time` is a
good way of exploring if important information has been ignored.

#### Sample swaps

If there have been a pair of samples swapped, this can be corrected in
the spec file.

```
    all = sample_set(
      subset = TRUE,
	  swap=list("A"="B")
```

This will swap the _metadata_ of sample with ID `A` with that of
sample ID `B`.  **Every** column of the metadata will be exchanged:
this is generally what is required (remember that `ID` is what is used
to connect the metadata to the correct quantified counts file):

```
ID Name Treatment Batch
A  T1   Treated   B1
B  C1   Control   B1
```

correctly becomes

```
ID Name Treatment Batch
A  C1   Control   B1
B  T1   Treated   B1
```

Tellings us that the contents of nfcore file `A.genes.results` are
from a control sample from batch B1. But if somehow the swap had not
affected the `Name`, and the situation that needed correcting was

```
ID Name Treatment Batch
A  C1   Treated   B1
B  T1   Control   B1
```

then you might want to consider fixing the anomaly manually (perhaps
via a `mutate`) as swapping around that table will result in the
somewhat confusingly "Named"

```
ID Name Treatment Batch
A  T1   Control   B1
B  C1   Treated   B1
```

(the correct association between A and "Control Batch 1" has been
made, but the name is now "off" - unimportant for the analysis, but
counter-intuitive).

#### Technical Replicates

Sometimes a scientist has done purely technical replicates. Ideally
these should be concatenated at the nfcore level, but sometimes they
get kept separate. We can correct for this in the spec file, for
example:

```
    all = sample_set(
      subset = TRUE,
	  collapse=~treatment + biological_replicate + timepoint + batch,
	  ...
```

The collapse formula should identify the distinct experimental groups,
so in the above formula we might expect that there are multiple
samples (rows in the experiment_table) with the same values for each
of those four variables; so there may be three rows with
`treatment=control`, `biological_replicate=3`, `timepoint=7hr` and
`batch=1` corresponding to three technical replicates. Ensure you have
enough terms in your model to distinguish all experimental conditions
and true replicates.

Keeping technical replicates in (without a `collapse`) is almost
always bad, as the standard errors are badly miscalculated.

#### Normalisation strategies

We can fine-tune which genes are analysed and which genes are used to
calculate size factors:

```
    all = sample_set(
      subset = TRUE,
      controlGenes=expression(grepl("^ercc", ID)),
	  subsetGenes=expression(symbol!=""),
	  ...
```

`controlGenes` and `subsetGenes` both take an R expression that should
evaluate to a boolean of the featureData of the dataset
(traditionally, `symbol` and `entrez` get set, and `ID` is my
convention for accessing the row.names (probably the ensembl ID). The
size factors are calculated on all rows that pass the controlGenes
filter, and then the subset filter is applied to all the original rows
(so one can calculate on the spike-ins, and then drop them out.)



### Settings

Other than the overall modelling strategy, it's important to be able
to tune the analysis by choosing the parameters behind the
algorithms. It's possible to set any parameters that the core analysis
script has made available to you through the `settings` top level
option:

```r
specification(
  sample_sets =list( 
  ...
  ),
 settings=settings(     ## analysis parameters
   alpha          = 0.05,    ## p-value cutoff
   lfcThreshold   = 0,       ## abs lfc threshold
   baseMeanMin    = 0,       ## discard transcripts with average normalised counts lower than this
   top_n_variable = 500,     ## For PCA
   showCategory   = 25,      ## For enrichment analyses
   seed           = 1,       ## random seed gets set at start of script, just in case.
   filterFun      = IHW::ihw ## NULL for standard DESeq2 results, otherwise  functions
    )
)
```

## Installation

It's necessary to configure git so that the author of any analyses you
create is correctly assigned; this is a one-off process if you haven't
done it before:

```bash
git config --global user.name "First Last"
git config --global user.email "first.last@crick.ac.uk"
```

### Installation into a project

TLDR:
```
ts worktree hash=ab123
```
will do the follow steps (you can do `ts -n worktree hash=ab123` to
see what it's going to do).


The whole pipeline is stored at
`/nemo/stp/babs/working/bioinformatics/templates/rnaseq.tar.gz`. This
archive is contains a `babs` folder that contains the logic, but also
includes a `.github` folder and a `.gitignore` file so watch out if
you want to preserve your existing copies of those. The expectation is
that the `babs` folder from the archive will live alongside the `.babs`
file: the only the other thing the pipeline needs is the `docs` folder
that is in the project's repo. You can either `git clone` that (from
nemo or from github), or you can create a `git worktree` from the nemo
copy which allows other users to see you have a branch. 

Some project repositories used to come with an old version of the
pipeline 'installed'. I recommend you remove that if applicable, just
leaving the `docs` folder out of the all the `./babs/` contents.

Once the projects has a `.babs` file and a `babs/docs` subfolder,
one can simply

```
 tar -xzf
 /nemo/stp/babs/working/bioinformatics/templates/rnaseq.tar.gz
 ```

to get the pipeline.


## Usage

### Whole pipeline

TLDR: `make all` in the `babs` folder will run the whole pipeline.

`cd` into the `./babs` folder, and there should be a makefile there,
along with folders for each 'module' of functionality.  `docs` is the
source of all truth; `ingress` will copy everything from `docs`
(a trivial operation, but if we ever change the 'API' this will allow
this reasonably easily). `nfcore` is the first non-trivial one -
quantify the counts.  And `differential` is the main body.  Each
module follows the same pattern. `make build` in a directory will
ensure that that directory is, henceforth, self-contained - so
e.g. for nfcore it will ensure that the samplesheet is in the
directory (rather than the `docs` folder where it originated
from). Once the directory is self-contained, `make run` can be
executed to generate the results from this module.

`make all` will do this build+run procedure in the logical manner for
you, but if it falls over, you can then go into the problematic module
and use either `make build` or `make run` (depending on where the
failure was) interactively to debug the problem.

### Just the differential part

If you're using the full bulk RNASeq pipeline, everything should be
set up for you. There will be a folder called `differential`. To get
the three main inputs, metadata needs to be transferred from the
`docs` folder (the original source of experiment table and spec files
that describe the analysis to be carried out), and data (the aligned
counts) need to be transferred from the `nfcore` module. Achieving
that should just be a matter of running `make build` in the
`differential` folder.  If you're taking counts etc from different
sources, then it's possible to join the pipeline just at this
`differential` stage by manually 'simulating' the `make build`. Set an
environment variable that stores a tag (alphanumeric please) that
identifies how you quantified your data: I'm going to use the tag
`GRCh38` as a toy value.  Then you'll need to achieve the following to
enable a manual analysis:

```
export alignment=GRCh38 # change `mytag` to a meaningful but arbitrary tag
mkdir -p extdata/genes.results/${alignment}

# change `path-to` to the right location!
cp /path-to/*.genes.results extdata/genes.results/${alignment}/

# First column is `ID` and its values match the extensionless basenames of *.genes.results
cp /path-to/experiment_table.csv extdata/metadata_${alignment}.csv
cp /path-to/spec.file .

# make sure XXX is the correct annotation package
echo "{alignment}.org.db=org.XXX.eg.db" > ${alignment}.config 
```

That should replace everything that a `make build` (now unnecessary)
would have done.

Following on from that, the folder will locally contain everything
needed for future analyses to be entirely self-contained: changes to
the local copies of the spec files and the contents of `extdata` are
sufficient (you _can_ copy changes back to their original source
modules for reference, but if the 'originals' remain older then they
won't overwrite these local copies even if another build is carried
out.)

### Differential analysis

The vast majority of work is carried out by:

```
# cd babs/differential
make run
```

which will discover all `spec` files in the current directory, and
analyse the data according to the analysis plan.

The rough steps this goes through is:

 - Set up a singularity environment that isolates a version of R and
   Quarto for reproducibility
 - Set up the R packages that are necessary to run the analysis
 - 'Join' the quarto scripts in the `resources` folder together with
   the spec files and count files, so that the `staging` folder
   contains scripts for all the analyses required.
 - Render the quarto 'project' that encompasses all these `staging`
   reports in the singularity container.
   
More often than not, the spec file from the initial design isn't
correct/sufficient. Editing it in place is absolutely fine, and a
repeat `make run` will take a fresh attempt. There's no harm in a `rm -rf staging` to 
clear out old scripts. Similarly the `results`
directory can get populated with old files - manually cleaning these out is fine from 
a pipeline-perspective.  But if you want to keep separate generations of results, it is worth performing
a `git tag` to bump the version of the analysis as this will put results in a separate subfolder.

The quarto report will be an html website.  The individual quarto
scripts get translated from their 'raw template' form in `resources`,
to their realised form in the `staging` directory.  These also produce
objects in the `data` folder for further bespoke analysis.

## Output

### R object

The _bioinformatician's output_ is contained in the
`data/counts_alignmentID.rda` object (where _alignmentID_ is the label
described in the very first part of this document). If you have R with
the working directory at the top level of our project, you will be
able to access it with

```
R> data(counts_alignmentID)
```

That is the pure DESeq2 data object prior to processing. We also store
the analysed data in `data/specID_x_alignmentID`
(where _specID_ identifies the name of the spec file used). This is a
triply-nested list, called `dds_model_comp`. The first corresponds to
the datasets, so for example

```
R> data(analysis_x_nfcore)
R> names(dds_model_comp)
[1] "all" "tumour" "normal"
```

corresponds to our situation where we analysed the tumour/normal
cohorts both together and individually. The next level of the list
corresponds to the models that were run on that dataset:

```
R> names(dds_model_comp$all)
[1] "accurate" "powerful"
```

might represent the two different approaches we used to account for a
potential batch effect. And finally the third level corresponds to the
individual comparisons:

```
R> names(default_dds$all$accurate)
[1] "comp1" "comp2" "comp3" "comp4"
R> class(default_dds$all$accurate$comp1
[1] "DESeqDataSet"
R> mcols(default_dds$all$accurate$comp1)$results
DataFrame with 19319 rows and 11 columns
                 baseMean log2FoldChange     lfcSE      stat      pvalue        padj    weight      symbol      entrez       class  shrunkLFC
                <numeric>      <numeric> <numeric> <numeric>   <numeric>   <numeric> <numeric> <character> <character> <character>  <numeric>

```

So we have the `results` stored in the `mcols` of each DESeqDataSet
that's stored in the third level of the list. You can use
``purrr:map_depth(default_dds, .depth=3)`` as one way of extracting
these, or loops, or ...

### HTML Report

We also generate a standard report of the results, most of the
sections being fairly self-explanatory. We may produce some more
documentation on this at some point.
