#!/usr/bin/env bash

image='${CONTAINER_IMAGE}'
overlay=${CONTAINER_OVERLAY_PATH}

basename=$(basename $0)
NUM_THREADS=2

cmd=${BABS_CMD:-${basename%-*}}

wd=$(git rev-parse --show-toplevel 2>/dev/null || echo $(realpath .))

if [[ -f Renviron-${RVERSION} ]]; then
    renvironBind=" --mount type=bind,source=$(realpath .)/Renviron-${RVERSION},target=/usr/local/lib/R/etc/Renviron.site "
else
    renvironBind=""
fi

if [[ -n "${DOCKER_BIND}" ]]; then
    echo "Warning: Extra directories being bound to the container: ${DOCKER_BIND}. This might affect reproducibility." 1>&2
fi
if compgen -v | grep DOCKERENV 1>&2; then
  echo "Warning: The above environment variables are used in the container. Remove the corresponding DOCKERENV_* variable if you don't want the following values to be used."
  for var in $(compgen -v | grep DOCKERENV); do
    echo "${var#DOCKERENV_}=${!var}" 1>&2
  done
fi


PASSWORD=$(openssl rand -base64 15)

export caller="${CONTAINER} ${CONTAINER_OPTIONS} ${image}"

seed=0
while :; do
    PORT=$(shuf -n 1 -i 49152-65535 --random-source=<(echo "${PWD}${seed}" | openssl dgst -sha256 | cut -d ' ' -f2 ))
    ss -atun sport ":$PORT" | grep -q ":$PORT" || break
    ((seed++))
done

rstudio_opts=""
bind_src=( "./run" "./database.conf"              "./rsession.sh"            "./var/lib/rstudio-server" "./rsession.conf"             "/rstudio"              "./R")
bind_tgt=( "/run"  "/etc/rstudio/database.conf"   "/etc/rstudio/rsession.sh" "/var/lib/rstudio-server"  "/etc/rstudio/rsession.conf"  "$HOME/.config/rstudio" "$HOME/.config/R")
bind_bth=( "/etc/ssl/certs/ca-bundle.crt" "$HOME/.ssh" "/sys/fs/cgroup" "./R:$HOME/.config/R")
for i in "${!bind_src[@]}"; do
    rstudio_opts+=" --mount type=bind,source=${bind_src[i]},target=${bind_tgt[i]}"
done
for i in "${!bind_bth[@]}"; do
    rstudio_opts+=" --mount type=bind,source=${bind_bth[i]},target=${bind_bth[i]}"
done


if [ "$cmd" == rstudio ]; then
    rstudio_opts+=" --env RSTUDIO_SESSION_TIMEOUT=0"
    rstudio_opts+=" --env USER=$(id -un)"
    rstudio_opts+=" --env PASSWORD=$PASSWORD"
    export caller="${CONTAINER} ${CONTAINER_OPTIONS} ${rstudio_opts} ${image}"    
    cd .babs-launchers
    source rstudio.sh
elif [ "$cmd" == shiny ]; then
    cd .babs-launchers
    source shiny.sh
elif [ "$cmd" == jupyter ]; then
    cd .babs-launchers
    source jupyter.sh
elif [ "$cmd" == shell ]; then
    eval "${caller/exec/shell}"
else
    eval "${caller} ${cmd} $@"
fi

