#!/usr/bin/env bash
#SBATCH --ntasks=1
#SBATCH --output=slurm-%x.out

image='${CONTAINER_IMAGE}'
overlay=${CONTAINER_OVERLAY_PATH}

if [ -z "${SLURM_JOB_ID}" ]; then
    basename=$(basename $0)
    NUM_THREADS=2
else
    basename=$(basename $(scontrol show job $SLURM_JOB_ID | awk -F= '/Command=/{print $2}'))
    NUM_THREADS=${SLURM_JOB_CPUS_PER_NODE}
    hname=babs002
fi


cmd=${BABS_CMD:-${basename%-*}}

if [[ -f Renviron.site ]]; then
    renvironBind=,$$(realpath .)/Renviron.site:/usr/local/lib/R/etc/Renviron.site
else
    renvironBind=""
fi

if [[ -n "${SINGULARITY_BIND}" ]]; then
    echo "Warning: Extra directories being bound to the container: ${SINGULARITY_BIND}. This might affect reproducibility." 1>&2
fi
if compgen -v | grep SINGULARITYENV 1>&2; then
  echo "Warning: The above environment variables are used in the container. Remove the corresponding SINGULARITYENV_* variable if you don't want the following values to be used."
  for var in $(compgen -v | grep SINGULARITYENV); do
    echo "${var#SINGULARITYENV_}=${!var}" 1>&2
  done
fi


PASSWORD=$(openssl rand -base64 15)

export caller="${CONTAINER} ${CONTAINER_OPTIONS} ${image}"

seed=0
while :; do
    PORT=$(shuf -n 1 -i 49152-65535 --random-source=<(echo "${PWD}${seed}" | openssl dgst -sha256 | cut -d ' ' -f2 ))
    ss -atun sport ":$PORT" | grep -q ":$PORT" || break
    ((seed++))
done


if [ "$cmd" == rstudio ]; then
    export SINGULARITYENV_RSTUDIO_SESSION_TIMEOUT=0
    export SINGULARITYENV_USER=$(id -un)
    export SINGULARITYENV_PASSWORD=$PASSWORD
    export SINGULARITY_BIND="./run:/run,./database.conf:/etc/rstudio/database.conf,\
./rsession.sh:/etc/rstudio/rsession.sh,./var/lib/rstudio-server:/var/lib/rstudio-server,\
./rsession.conf:/etc/rstudio/rsession.conf,./R:$HOME/.config/R,./rstudio:$HOME/.config/rstudio,\
/etc/ssl/certs/ca-bundle.crt,$HOME/.ssh,/sys/fs/cgroup"
    cd .babs-launchers
    source rstudio.sh
elif [ "$cmd" == shiny ]; then
    cd .babs-launchers
    source shiny.sh
elif [ "$cmd" == jupyter ]; then
    cd .babs-launchers
    source jupyter.sh
elif [ "$cmd" == shell ]; then
    eval "${caller/exec/shell}"
else
    eval "${caller} ${cmd} $@"
fi

