#' R6 class representing the set of parameters used in an analysis
#' 
#' @export
ParamList <- R6::R6Class("ParamList",
                        private = list(
                          params=list(),
                          descriptions=list(alpha="The threshold of statistical significance is {}",
                                            lfcThreshold="The threshold for absolute effect size is {}",
                                            title="The name of the project is '{}'",
                                            top_n_variable="Only use {} features for unsupervised clustering",
                                            script="The project was generated by '{}'",
                                            showCategory= "Only show top {} enriched categories in plots",
                                            seed="A random seed of {} is used to ensure reproduciblity",
                                            filterFun="{Default} independent filtering",
                                            gene_clust="{}",
                                            impute="Imputation method: {Not applicable}",
                                            normalise="Normalisation: {Standard DESeq2 approach}",
                                            showStringsAsFactors="Convert strings to factors in the experiment table? - {}",
                                            baseMeanMin="Discard transcripts with few average counts per sample than {}",
                                            baseline_heuristic="Use the '{}' heuristic to centre the colour-scale",
                                            reduce_heuristic="Use the '{}' terms heuristic to test covariate-PC associations",
                                            pc_weight="Use the '{}' heuristic to choose strength of PC-covariate association",
                                            LRT_effect="Use the '{}' summary of an LRT 'effect size'"
                                            ),
                          defaults=list(),
                          div_contents=""
                        ),
                        public = list(
                          #' @description
                          #' Create a new set of parameters.
                          #' @param defaults Named list of default values.  Names are the parameters, and the values will be their default.
                          #' @return An object that will store all future values of analysis parameters.
                          initialize = function(defaults=list()) {
                            private$defaults <- defaults
                          },
                          #' @description
                          #' Set the value of a parameter
                          #' @param id The name of the parameter to be set.
                          #' @param value The value the parameter should taken henceforth; if missing, it will take the default value.
                          #' @param description A string describing what the purpose of the parameter is.
                          #' @param div Logical, whether to mention in the markdown report what the value has been set to.
                          set = function(id, value, description="", postpone=FALSE) {
                            if (missing(value)) {
                              if (id %in% names(private$defaults)) {
                                value <- private$defaults[[id]]
                              } else {
                                eg <- default_spec_settings()
                                eg <- eg[grep(paste0("^\\s+", id),eg)]
                                if (length(eg)>0) {
                                  stop("Attempt to set '", id, "' but no value or default provided.\n", "You may need to update your spec file, as new settings have been introduced.  Maybe lines like:\n", paste(eg, collapse="\n"))
                                } else {
                                  stop("Attempt to set '", id, "' but no value or default provided.\n")
                                }
                              }
                            }
                            if (is.null(value)) {
                              private$params[id] <- list(NULL)
                            } else {
                              private$params[[id]]=value
                            }
                            if (description=="") {
                              if (!(id %in% names(private$descriptions))) { # provide tautological definition if 
                                description=paste0("The value of ", id, " is {}")
                              } else {
                                description=private$descriptions[id]}
                            }
                            if ("src" %in% names(attributes(value))) {
                              description <- gsub("\\{\\}", attr(value, "src"), description)
                            } else {
                              if (is.null(value)) {
                                description <- gsub("\\{([^}]*)\\}", "\\1", description)
                              } else {
                                description <- gsub("\\{\\}", value, description)
                              }
                            }
                            private$descriptions[[id]]=description
                            private$div_contents <- paste(private$div_contents, " - ", self$describe(id), '\n')
                            if ((!postpone) && isTRUE(getOption('knitr.in.progress'))) {
                              cat('\n\n::: {.callout-note title="Setting analysis parameter"}\n', private$div_contents, '\n:::\n\n')
                              private$div_contents <- ""
                            }
                            if (is.na(postpone)) {
                              private$div_contents <- ""
                            }
                            invisible(self$get(id))
                          },
                          #' @description
                          #' Get the value that the parameter is currently set to.
                          #' @param id Name of the value you want to access.
                          get = function(id, override) {
                            if (!missing(override) && (id %in% names(override))) {
                              return(override$id)
                            }
                            if (!id %in% names(private$params)) {
                              stop(id, " has not yet been initialized")
                            }
                            ret <- private$params[[id]]
                            if (is.call(ret)) eval(ret) else ret
                          },
                          #' @description
                          #' Turn the mutable object into a list
                          publish = function() {
                            lapply(private$params, eval)
                          },
                          #' @description
                          #' Get a text description of what the setting is, and what value it currently takes.
                          #' @param id Name of the value you want to access.
                          describe = function(id) {
                            if (missing(id)) {
                              private$descriptions[names(private$params)]
                            } else {
                              private$descriptions[[id]]
                            }
                          }
                        )
                        )

#' @export
counter <- function(post_fn=identity) {
  inds <- new.env(parent = emptyenv())
  function(label=".global") {
    if (exists(label, envir=inds, inherits=FALSE)) {
      inds[[label]] <- inds[[label]] + 1
    } else {
      inds[[label]] <- 1
    }
    post_fn(inds[[label]])
  }
}

#' @export
map_dmc <- function(data, f, depth="comparison",...) {
  if (class(data[[1]])!="list" || depth=="dataset") {
    return(map(data,f, ...))
  }
  if (class(data[[1]][[1]])!="list" || depth=="model") {
    return(map_depth(data, 2, f, ...))
  }
  map_depth(data, 3, f, ...)
}




#' Descend a result-tree
#'
#' Scripts create a Dataset > Model > Comparison nested list,
#' with everything stored at the third level of this list. results_apply
#' provides a way to traverse this list, applying a function to each dds object,
#' and reporting the results of that function aggregated to a particular level.
#'
#' For instance, the counts are universal to every model within a dataset, and
#' also to every comparison done within each model in that dataset.  But the
#' actual fitted coeffecients are specific to each comparison.
#' 
#' @title Apply a function to a results list
#' @param object The list of results returned by get_result
#' @param dataset The name of the dataset you want to restrict the traversal to - optional, and if omitted all datasets will be traversed.
#' @param model The name of the model you want to restrict the traversal to - optional, and if omitted all models will be traversed.
#' @param comparison The name of the comparison you want to restrict the traversal to - optional, and if omitted all comparisons will be traversed.
#' @param fn The function that should be applied to each dds object encountered
#' @param depth The depth to which traversal should be carried out.
#' @return A (nested) list of values that represent the return value of fn on the corresponding dds
#' @author Gavin Kelly
#' @export
results_apply <- function(object, dataset, model, comparison, fn, depth="comparison") {
  if (!missing(dataset)) {
    if (!missing(model)) {
      if (!missing(comparison)) {
        return(fn(object[[dataset]][[model]][[comparison]]))
      } else {
        ret <- lapply(
          names(object[[dataset]][[model]]),
          function(comp) results_apply(object, dataset, model, comp, fn, depth)
        )
        if (depth != "comparison") {
          if (all(sapply(ret, function(x) identical(x, ret[[1]])))) {
            ret <- ret[[1]]
          } else {
            stop("Summarising at the level of ", depth, " but some comparisons are different")
          }
        }
        return(ret)
      }
    } else {
      ret <- lapply(
        names(object[[dataset]]),
        function(mdl)  results_apply(object, dataset, mdl, fn=fn, depth=depth)
      )
      if (!(depth %in% c("comparison", "model"))) {
        if (all_identical(ret)) {
          ret <- ret[[1]]
        } else {
          stop("Summarising at the level of ", depth, " but some models are different")
        }
      }
      return(ret)
    }
  } else {
    ret <- lapply(
      names(object),
      function(dset)  results_apply(object, dset, fn=fn, depth=depth)
    )
    return(ret)
  }
}








#' Map over each component of a DESeq nested  object
#'
#' If you want to loop through datasets that have been fitted,
#' then use this function as a wrapped so that reports
#' can generate formatted output, and transformations can be applied.
#'
#' This should be the first process in a pipeline, and be followed by
#' either a per_model or per_comparison call: the primary function .f
#' will be applied to the output.  For each dataset in the dds
#' object, the 'before' function will be called before passing things
#' on (and so can be used to print a header, for example), and the
#' 'after' function will be called after (to produce captions).  All
#' functions have access to a variable '.dataset' that will take the
#' name of the current dataset
#' 
#' @title Wrap dataset-model-comparison object
#' @param .dmc A three-level list in the standard hierarchy dataset > model > comparison
#' @param .f The function that will be called on the output of the per_model or per_comparison.
#' @param before A function that will be invoked before .f
#' @param after A function that will be invoked after .f
#' @return The return value of .f, as applied to the list of child outputs
#' @author Gavin Kelly 




#' @export
dataset_name <- function(dds) {
  metadata(dds)$dmc$dataset
}
#' @export
model_name <- function(dds) {
  metadata(dds)$dmc$model
}
#' @export
comparison_name <- function(dds) {
  metadata(dds)$dmc$comparison
}





#' rbind nested lists of data-frames
#'
#' Walk through a 3-deep hierarchy of summaries, and join them
#' into one big summary table
#' @title rbind nested lists of data-frames
#' @param x the list of summaries
#' @param levels The vector of names of the levels of the hierarchy that will be used in the data-frame
#' @return The big table
#' @author Gavin Kelly
#' @export
rbind_summary <- function(x, levels=c("Dataset", "Design", "Comparison")) {
  if (class(x[[1]])=="list") {
    do.call(rbind, mapply(function(df, name) {
      extended <- cbind(name, df)
      names(extended)[1] <- levels[1]
      return(extended)
    }, lapply(x, rbind_summary, levels[-1]), names(x), SIMPLIFY=FALSE))
  } else {
    do.call(rbind, mapply(function(df, name) {
      extended <- cbind(name, df)
      names(extended)[1] <- levels[1]
      return(extended)
    }
   ,x, names(x), SIMPLIFY=FALSE))
  }
}




#' Convert dataset-model-comparison hierarchy into data.frame
#'
#' Create a data.frame with columns for dataset, model, and comparison
#' alongside a list-column containing the dds object
#' @title Convert DMC to dataframe
#' @param dmc A triple-level list
#' @return A data.frame of the expanded list
#' @author Gavin Kelly
#' @export
dmc2df <- function(dmc) {
  dds <- do.call(c, lapply(dmc, function(d) {do.call(c, lapply(d, function(m) {m}))}))
  df <- tibble::tibble(
    dataset=sapply(dds, function(x) metadata(x)$dmc$dataset),
    model=sapply(dds, function(x) metadata(x)$dmc$model),
    comparison=make.unique(sapply(dds, function(x) metadata(x)$dmc$comparison)),
    dds=I(dds)
  )
  df
}

#' @export
choose_staging <- function(resource, staging="staging") {
  files <- dir(staging, pattern=paste0("^", resource, ".*\\.qmd"))
  if (length(files)==1) {
    print(paste("Using parameters from", files))
    file.path(staging, sub(".qmd$", "", files))
  } else if (length(files)==0) {
    warning("No staging files from which to take parameters.")
  } else {    
    file.path(staging, sub(".qmd$", "", files[menu(files, title="Select which staging file to use for parameters")]))
  }
}




#' @export
get_align_params <- function(name) {
  my_config <- readLines(paste0(file.path("extdata", name), ".config"))
  align_params <- strsplit(sub(paste0("^", name, "\\."),
                              "",
                              my_config), "=")
  names(align_params) <- sapply(align_params, "[", 1)
  lapply(align_params, function(x) sub("*#.*$", "", x[[2]]))
}

noun_to_readout <- function(noun) {
  readout <- list(
    "protein"="abundance",
    "gene"="expression"
  )
  if (stringr::str_to_lower(noun) == noun)
    default <- "readout"
  else
    default <- "Readout"
  default <- 
    attr(noun, "readout") %||%
    readout[[noun]] %||%
    stringr::str_to_title(readout[[stringr::str_to_lower(noun)]]) %||%
    default
  default
}


#' @export
setFirstAssay <- function(dds, ...) {
  fst <- list(...)[[1]]
  if (is.character(fst)) {
    nm <- fst
  } else {
    nm <- names(list(...))[1]
    assay(dds, nm) <- fst
  }
    assays(dds)[c(nm, setdiff(assayNames(dds), nm))]
}

#' @export
formula_equal <- function(f1, f2) {
  t1 <- attr(terms(f1), "term.labels")
  t2 <- attr(terms(f2), "term.labels")
  setequal(t1, t2)
}


#' @export
top_true <- function(is_in, stat, n, sym=TRUE) {
      ind <- which(is_in)[order(stat[is_in])]
      top_ind <- 1:min(n,length(ind))
      if (sym) {
        ind[unique(c(top_ind, sum(is_in)+1-top_ind))]
      } else {
        ind[top_ind]
      }
}

attach_src <- function(spec, src) {
  if (!"list" %in% class(spec)) {
    try(attr(spec, "src") <- src, silent=TRUE)
    return(spec)
  }
  out <- Map(attach_src, spec, src)
  attributes(out) <- attributes(spec)
  out
}


default_spec_settings <- function() {
  ex <- alist(         ## analysis parameters
    alpha          = 0.01,    ## p-value cutoff
    lfcThreshold   = 0,       ## abs lfc threshold
    baseMeanMin    = 0,       ## discard transcripts with average normalised counts lower than this
    top_n_variable = 500,     ## For PCA
    showCategory   = 25,      ## For enrichment analyses
    seed           = 1,       ## random seed gets set at start of script, just in case.
    gene_clust     = bluster::HclustParam(cut.params = list(k = 12)),   ## When we need to chose clusters of genes, how many?
    sample_clust   = bluster::HclustParam(metric="pearson"),
    filterFun      = IHW::ihw,                 ## NULL for standard DESeq2 results, otherwise  functions
    stringsAsFactors = FALSE,
    normalise=NULL,
    impute=NULL,
    baseline_heuristic = "min",  ## For the "white" colour in differential heatmaps
    pc_weight = "equal weight", ## equal_weight/eigen (latter favours early PCs)
    reduce_heuristic="drop1",
    LRT_effect = "default"  ## For the "white" colour in differential heatmaps
  )
  attach_src(lapply(ex, eval), lapply(ex, function(x) paste(deparse(x), collapse="")))
}



#' @export
design <- function(x) {
  if (methods::is(x, "DESeqDataSet")) {
    DESeq2::design(x)
  } else if (inherits(x, "SummarizedExperiment")) {
    metadata(x)$design
  } else {
    stop("design() not defined for this object")
  }
}

#' @export
`design<-` <- function(x, value) {
  if (methods::is(x, "DESeqDataSet")) {
    # call DESeq2 S4 setter
   DESeq2::`design<-`(x, value=value)
  } else if (inherits(x, "SummarizedExperiment")) {
    metadata(x)$design <- value
    x
  } else {
    stop("design<- not defined for this object")
  }
}

split_conjuncts <- function(expr) {
  if (is.call(expr) && identical(expr[[1]], as.name("&"))) {
    c(
      split_conjuncts(expr[[2]]),
      split_conjuncts(expr[[3]])
    )
  } else {
    list(expr)
  }
}

accumulate_predicates <- function(preds, deps, target=NULL, pred=TRUE) {
  if (!is.null(target) && !target %in% names(deps)) return(pred)
  for (i in names(preds)) {
    if (!is.null(target) && i==target) {
      return( pred  & Reduce(`&`, preds[intersect(names(preds), deps[[i]])]) )
    }
    if (i %in% names(deps)) {
      preds[[i]] <- preds[[i]] & Reduce(`&`, preds[intersect(names(preds), deps[[i]])])
    }
  }
  preds
}
