#' R6 class representing the set of parameters used in an analysis
#' 
#' @export
ParamList <- R6::R6Class("ParamList",
                        private = list(
                          params=list(),
                          descriptions=list(alpha="The threshold of statistical significance is {deparse(alpha)}",
                                            lfcThreshold="The threshold for absolute effect size is {}",
                                            title="The name of the project is '{}'",
                                            top_n_variable="Only use {} genes for unsupervised clustering",
                                            script="The project was generated by '{}'",
                                            showCategory= "Only show top {} enriched categories in plots",
                                            seed="A random seed of {} is used to ensure reproduciblity",
                                            filterFun="{if (is.null(filterFun)) 'Default' else deparse(filterFun)} independent filtering",
                                            gene_clust="{if (is.null(gene_clust)) 'Default' else deparse(gene_clust)}",
                                            baseMeanMin="Discard transcripts with few average counts per sample than {}",
                                            baseline_heuristic="Use the '{}' heuristic to centre the colour-scale",
                                            LRT_effect="Use the '{}' summary of an LRT 'effect size'"
                                            ),
                          defaults=list(),
                          div_contents=""
                        ),
                        public = list(
                          #' @description
                          #' Create a new set of parameters.
                          #' @param defaults Named list of default values.  Names are the parameters, and the values will be their default.
                          #' @return An object that will store all future values of analysis parameters.
                          initialize = function(defaults=list()) {
                            private$defaults <- defaults
                          },
                          #' @description
                          #' Set the value of a parameter
                          #' @param id The name of the parameter to be set.
                          #' @param value The value the parameter should taken henceforth; if missing, it will take the default value.
                          #' @param description A string describing what the purpose of the parameter is.
                          #' @param div Logical, whether to mention in the markdown report what the value has been set to.
                          set = function(id, value, description="", postpone=FALSE) {
                            if (missing(value)) {
                              if (id %in% names(private$defaults)) {
                                value <- private$defaults[[id]]
                              } else {
                                eg <- default_spec_settings()
                                eg <- eg[grep(paste0("^\\s+", id),eg)]
                                if (length(eg)>0) {
                                  stop("Attempt to set '", id, "' but no value or default provided.\n", "You may need to update your spec file, as new settings have been introduced.  Maybe lines like:\n", paste(eg, collapse="\n"))
                                } else {
                                  stop("Attempt to set '", id, "' but no value or default provided.\n")
                                }
                              }
                            }
                            if (is.null(value)) {
                              private$params[id] <- list(NULL)
                            } else {
                              private$params[[id]]=value
                            }
                            if (description=="") {
                              if (!(id %in% names(private$descriptions))) { # provide tautological definition if 
                                description=paste0("The value of ", id, " is {", id, "}")
                              } else {
                                description=private$descriptions[id]}
                            } 
                            description <- gsub("\\{\\}", paste0("{", id, "}"), description)
                            private$descriptions[[id]]=description
                            private$div_contents <- paste(private$div_contents, " - ", self$describe(id), '\n')
                            if ((!postpone) && isTRUE(getOption('knitr.in.progress'))) {
                              cat('\n\n::: {.callout-note title="Setting analysis parameter"}\n', private$div_contents, '\n:::\n\n')
                              private$div_contents <- ""
                            }
                            if (is.na(postpone)) {
                              private$div_contents <- ""
                            }
                            invisible(self$get(id))
                          },
                          #' @description
                          #' Get the value that the parameter is currently set to.
                          #' @param id Name of the value you want to access.
                          get = function(id, override) {
                            if (!missing(override) && (id %in% names(override))) {
                              return(override$id)
                            }
                            if (!id %in% names(private$params)) {
                              stop(id, " has not yet been initialized")
                            }
                            ret <- private$params[[id]]
                            if (is.call(ret)) eval(ret) else ret
                          },
                          #' @description
                          #' Turn the mutable object into a list
                          publish = function() {
                            lapply(private$params, eval)
                          },
                          #' @description
                          #' Get a text description of what the setting is, and what value it currently takes.
                          #' @param id Name of the value you want to access.
                          describe = function(id) {
                            if (missing(id)) {
                              purrr::map(private$descriptions[names(private$params)],  function(d) glue::glue_data(.x =private$params, d))
                            } else {
                              glue::glue_data(private$params,
                                              private$descriptions[[id]])
                            }
                          }
                        )
                        )

counter <- function() {
  inds <- list()
  function(label) {
    if (label %in% names(inds)) {
      inds[[label]] <<- inds[[label]] + 1
    } else {
      inds[[label]] <<- 1
    }
    paste0(label, "-", inds[[label]])
  }
}

map_dmc <- function(data, f, depth="comparison",...) {
  if (class(data[[1]])!="list" || depth=="dataset") {
    return(map(data,f, ...))
  }
  if (class(data[[1]][[1]])!="list" || depth=="model") {
    return(map_depth(data, 2, f, ...))
  }
  map_depth(data, 3, f, ...)
}



all_identical <- function(obj)  {all(sapply(obj, function(x) identical(x, obj[[1]])))}

#' Descend a result-tree
#'
#' Scripts create a Dataset > Model > Comparison nested list,
#' with everything stored at the third level of this list. results_apply
#' provides a way to traverse this list, applying a function to each dds object,
#' and reporting the results of that function aggregated to a particular level.
#'
#' For instance, the counts are universal to every model within a dataset, and
#' also to every comparison done within each model in that dataset.  But the
#' actual fitted coeffecients are specific to each comparison.
#' 
#' @title Apply a function to a results list
#' @param object The list of results returned by get_result
#' @param dataset The name of the dataset you want to restrict the traversal to - optional, and if omitted all datasets will be traversed.
#' @param model The name of the model you want to restrict the traversal to - optional, and if omitted all models will be traversed.
#' @param comparison The name of the comparison you want to restrict the traversal to - optional, and if omitted all comparisons will be traversed.
#' @param fn The function that should be applied to each dds object encountered
#' @param depth The depth to which traversal should be carried out.
#' @return A (nested) list of values that represent the return value of fn on the corresponding dds
#' @author Gavin Kelly
#' @export
results_apply <- function(object, dataset, model, comparison, fn, depth="comparison") {
  if (!missing(dataset)) {
    if (!missing(model)) {
      if (!missing(comparison)) {
        return(fn(object[[dataset]][[model]][[comparison]]))
      } else {
        ret <- lapply(
          names(object[[dataset]][[model]]),
          function(comp) results_apply(object, dataset, model, comp, fn, depth)
        )
        if (depth != "comparison") {
          if (all_identical(ret)) {
            ret <- ret[[1]]
          } else {
            stop("Summarising at the level of ", depth, " but some comparisons are different")
          }
        }
        return(ret)
      }
    } else {
      ret <- lapply(
        names(object[[dataset]]),
        function(mdl)  results_apply(object, dataset, mdl, fn=fn, depth=depth)
      )
      if (!(depth %in% c("comparison", "model"))) {
        if (all_identical(ret)) {
          ret <- ret[[1]]
        } else {
          stop("Summarising at the level of ", depth, " but some models are different")
        }
      }
      return(ret)
    }
  } else {
    ret <- lapply(
      names(object),
      function(dset)  results_apply(object, dset, fn=fn, depth=depth)
    )
    return(ret)
  }
}

#' Return all results contained in a result list
#'
#' Traverse an object returned by get_result, and extract the DESeq2 results stored at each node.
#' @title Return all results contained in a result list
#' @param object The list of results returned by get_result
#' @param dataset The name of the dataset you want to restrict the traversal to - optional, and if omitted all datasets will be traversed.
#' @param model The name of the model you want to restrict the traversal to - optional, and if omitted all models will be traversed.
#' @param comparison The name of the comparison you want to restrict the traversal to - optional, and if omitted all comparisons will be traversed.
#' @return 
#' @author Gavin Kelly
#' @export
extract_results <- function(object, dataset, model, comparison ) {
  results_apply(object, dataset, model, comparison, fn=function(dds) mcols(dds)$results, depth="comparison")
}


extract_model <- function(object, dataset) {
  results_apply(object, dataset, fn=function(dds) mcols(dds)$results, depth="model")
}

#' Return an assay from a result-list
#'
#' Traverse an object returned by get_result, and extract a specific assay
#' @title Return an assay from a result-list
#' @param dataset The name of the dataset you want to extract the assay from  - optional, and if omitted all datasets will be reported.
#' @param object The list of results returned by get_result
#' @param assay The name of the assay you want to extract from each dataset
#' @return 
#' @author Gavin Kelly
#' @export
extract_assay <- function(object,dataset,  assay) {
  results_apply(object, dataset, fn=function(dds) assay(dds, assay), depth="dataset")
}  


#' Return PCA-projected data from a result-list
#'
#' Traverse an object returned by get_result, and extract the expression projected onto PC space.
#' The models, and comparisons within those, should all have the same projections, so the results
#' are aggregated to the level of 'dataset'
#' @title Return PCA-projected data from a result-list
#' @param dataset The name of the dataset you want to extract the PC coordinates  - optional, and if omitted all datasets will be reported.
#' @param object The list of results returned by get_result
#' @return A DataFrame of PC coordinates for each dataset specified
#' @author Gavin Kelly
#' @export
extract_pca_x <- function(object, dataset) {
  results_apply(object, dataset, fn=function(dds) colData(dds)$.PCA, depth="dataset")
}

#' Return colData from a result-list
#'
#' Traverse an object returned by get_result, and extract the colData. As the
#' comparisons and models within a dataset are all based off the same colData,
#' the return value is aggregated to the level of dataset.
#' @title Return PCA-projected data from a result-list
#' @param dataset The name of the dataset you want to extract the PC coordinates  - optional, and if omitted all datasets will be reported.
#' @param object The list of results returned by get_result
#' @return A DataFrame of PC coordinates for each dataset specified
#' @author Gavin Kelly
#' @export
extract_colData <- function(object, dataset) {
  results_apply(object, dataset, fn=function(dds) colData(dds), depth="dataset")
}



#' Map over each component of a DESeq nested  object
#'
#' If you want to loop through datasets that have been fitted,
#' then use this function as a wrapped so that reports
#' can generate formatted output, and transformations can be applied.
#'
#' This should be the first process in a pipeline, and be followed by
#' either a per_model or per_comparison call: the primary function .f
#' will be applied to the output.  For each dataset in the dds
#' object, the 'before' function will be called before passing things
#' on (and so can be used to print a header, for example), and the
#' 'after' function will be called after (to produce captions).  All
#' functions have access to a variable '.dataset' that will take the
#' name of the current dataset
#' 
#' @title Wrap dataset-model-comparison object
#' @param .dmc A three-level list in the standard hierarchy dataset > model > comparison
#' @param .f The function that will be called on the output of the per_model or per_comparison.
#' @param before A function that will be invoked before .f
#' @param after A function that will be invoked after .f
#' @return The return value of .f, as applied to the list of child outputs
#' @author Gavin Kelly 


#' @export
trim_map <- function(data) {
  deeper <- !sapply(data, is.null)
  if (!any(deeper)) {
    return(NULL)
  }
  lapply(data[deeper], function(x) {if (class(x)=="list") trim_map(x) else x})
}


#' @export
dataset_name <- function(dds) {
  metadata(dds)$dmc$dataset
}
#' @export
model_name <- function(dds) {
  metadata(dds)$dmc$model
}
#' @export
comparison_name <- function(dds) {
  metadata(dds)$dmc$comparison
}



#' @export
dmc2frame <- function(dmc) {
  df_rows <- map_dmc(dmc, function(x) {
    data.frame(dataset=dataset_name(x),
               model=model_name(x),
               comparison=comparison_name(x))
  })
  df <- unlist(unlist(df_rows, recursive=FALSE), recursive=FALSE)
  dds <- unlist(unlist(dmc, recursive=FALSE), recursive=FALSE)[names(df)]
  df <- do.call(rbind, df)
  df$dds <- dds
  df
}




##' rbind nested lists of data-frames
##'
##' Walk through a 3-deep hierarchy of summaries, and join them
##' into one big summary table
##' @title rbind nested lists of data-frames
##' @param x the list of summaries
##' @param levels
##' @return The big table
##' @author Gavin Kelly
##' @export
rbind_summary <- function(x, levels=c("Dataset", "Design", "Comparison")) {
  if (class(x[[1]])=="list") {
    do.call(rbind, mapply(function(df, name) {
      extended <- cbind(name, df)
      names(extended)[1] <- levels[1]
      return(extended)
    }, lapply(x, rbind_summary, levels[-1]), names(x), SIMPLIFY=FALSE))
  } else {
    do.call(rbind, mapply(function(df, name) {
      extended <- cbind(name, df)
      names(extended)[1] <- levels[1]
      return(extended)
    }
   ,x, names(x), SIMPLIFY=FALSE))
  }
}


## classify_terms <- function(fml) {
##   has_random <- any(c("|", "||") %in% all.names(fml))
##   if (!has_random) {
##     return(list(fixed=all.vars(fml),groups=list() ))
##   }
##   rterms <- lme4:::barnames(lme4::findbars(fml))
##   rterms <- sub(":.*", "", rterms)
##   fvars <- setdiff(all.vars(lme4::subbars(fml)), rterms)
##   list(fixed=fvars, groups=rterms)
## }
##' .. content for \description{} (no empty lines) ..
##'
##' .. content for \details{} ..
##' @title 
##' @param fml 
##' @return 
##' @author Gavin Kelly
classify_terms <- function(fml) {
  rhs <- as.character(fml)[length(fml)]
  spl <- strsplit(rhs, "|", fixed=TRUE)[[1]]
  rv <- all.vars(stats::reformulate(spl[1]))
  list(
    fixed=rv,
    groups=setdiff(all.vars(stats::reformulate(rhs)), rv)
  )
}


##' Convert dataset-model-comparison hierarchy into data.frame
##'
##' Create a data.frame with columns for dataset, model, and comparison
##' alongside a list-column containing the dds object
##' @title Convert DMC to dataframe
##' @param dmc A triple-level list
##' @return A data.frame of the expanded list
##' @author Gavin Kelly
dmc2df <- function(dmc) {
  dds <- do.call(c, lapply(dmc, function(d) {do.call(c, lapply(d, function(m) {m}))}))
  list2DF(
    list(dataset=sapply(dds, function(x) metadata(x)$dmc$dataset),
    model=sapply(dds, function(x) metadata(x)$dmc$model),
    comparison=make.unique(sapply(dds, function(x) metadata(x)$dmc$comparison)),
    dds=dds
    )
  )
}

choose_staging <- function(resource, staging="staging") {
  files <- dir(staging, pattern=paste0("^", resource, ".*\\.qmd"))
  if (length(files)==1) {
    print(paste("Using parameters from", files))
    file.path(staging, sub(".qmd$", "", files))
  } else if (length(files)==0) {
    warning("No staging files from which to take parameters.")
  } else {    
    file.path(staging, sub(".qmd$", "", files[menu(files, title="Select which staging file to use for parameters")]))
  }
}

nclust <- function(npclust, universe=1) {
  if (npclust<1) {
    # gene_clust is proportion of genelist
    floor(universe * npclust)
  } else {
    npclust
  }
}

rmod <- function(x, base, out=integer()) {
  if (x<base) {
    c(x, out)
  } else {
    rmod(x %/% base, base, out=c(x %% base, out))
  }
}

itoABC <- function(i) {
  paste0(LETTERS[rmod(i-1,26)+1], collapse="")
}
  
